### ISSUE TITLE
There is another to-string-loader

### ISSUE THREAD

**Issue by nicotoumetis** [smithad15/css-to-string-loader#4]
https://github.com/gajus/to-string-loader

This also works with css-loader and angular2 components. Not a big deal as the implementation are so simple. But you may want to consider merging your two modules :)

**Comment by smithad15** [comment]
You are correct. Different ways to do the same result. I will leave it up to each developer to make their own choices 🙂

**Comment by OzzieOrca** [comment]
For anyone else comparing these, the [exports-loader](https://webpack.js.org/loaders/exports-loader) seems to accomplish the same thing if you use it like this:
`exports-loader?module.exports.toString()`

I found it used by the Angular CLI at https://github.com/angular/angular-cli/blob/67646796d977bd476c3f618dd64a6c2b6c4ddcae/packages/%40angular/cli/models/webpack-configs/styles.ts#L174.
