### ISSUE TITLE
Add option for CSS source maps

### ISSUE THREAD

**Issue by Mario-Eis** [smithad15/css-to-string-loader#5]
As far as i can tell, source maps are ignored while doing toString.

e.g. they are handled in the style-loader: https://github.com/webpack-contrib/style-loader/blob/9dc45a6dee16553a64071031d18feb1562df86a2/addStyles.js

**Comment by smithad15** [comment]
It looks like `css-loader` has implemented source map support in v0.27.0 according to this commit: https://github.com/webpack-contrib/css-loader/commit/6da7e90. Since this is a function of `css-loader` and seems to be fixed upstream, I'm closing this issue as resolved.
